# Generated by Django 4.2.6 on 2023-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="Previous Lecture", max_length=256)),
                (
                    "engagement_ratio",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("tone_modality", models.DecimalField(decimal_places=1, max_digits=3)),
                ("questions", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
