# Generated by Django 4.2.6 on 2023-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectures",
            name="engagement_ratio",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="lectures",
            name="questions",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="lectures",
            name="tone_modality",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
