# Generated by Django 4.2.6 on 2023-10-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_alter_lectures_engagement_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectures",
            name="suggestion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="lectures",
            name="wpm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
