# Generated by Django 4.2.6 on 2023-10-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_lectures_suggestion_lectures_wpm"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectures",
            name="graph",
            field=models.TextField(blank=True, null=True),
        ),
    ]
