# Generated by Django 4.2.6 on 2023-10-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Video",
        ),
    ]
